### ISSUE TITLE
Peer dependency warnings

### ISSUE THREAD

**Issue by cherewaty** [image-js/fast-bmp#9]
I'm getting a couple peer dependency warnings when installing `image-js` in `yarn` `1.22.4` workspace:
```image-js > fast-bmp > eslint-config-cheminfo@8.0.2" has unmet peer dependency "eslint-plugin-jest@^26.4.6".```
```image-js > fast-bmp > eslint-config-cheminfo@8.0.2" has unmet peer dependency "eslint-plugin-jsdoc@^39.3.2".```

Should `eslint-config-cheminfo` be a `devDependency` of `fast-bmp` instead of a `dependency`?

**Comment by targos** [comment]
Thanks for the report. You're right, it should be in `dependencies`
